# Generated by Django 3.1.13 on 2021-09-15 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_pass', models.BooleanField(default=False, verbose_name='Pass')),
                ('record_comments', models.CharField(blank=True, max_length=500, verbose_name='Comments')),
                ('record_type', models.CharField(choices=[('MOISTURE_CONTENT', 'Moisture Content'), ('SIZE_CHECK', 'Size Check'), ('KILN_TIME', 'Kiln Time')], default='MOISTURE_CONTENT', max_length=20, verbose_name='Record Types')),
                ('moisture_content', models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='Moisture Content')),
                ('measured_width', models.PositiveIntegerField(null=True, verbose_name='Measured Width(mm)')),
                ('measured_depth', models.PositiveIntegerField(null=True, verbose_name='Measured Depth(mm)')),
                ('kiln_start_time', models.DateTimeField(null=True, verbose_name='Kiln Start Time')),
                ('kiln_finish_time', models.DateTimeField(null=True, verbose_name='Kiln Finish Time')),
            ],
            options={
                'verbose_name': 'Record',
                'verbose_name_plural': 'Records',
                'abstract': False,
            },
        ),
    ]
